<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <AssemblyName>TickLab</AssemblyName>
    <RootNamespace>TickLab.Desktop</RootNamespace>
    <Version>1.13.0.172</Version>
    <AssemblyVersion>1.13.0.172</AssemblyVersion>
    <FileVersion>1.13.0.172</FileVersion>
    <RestoreIgnoreFailedSources>true</RestoreIgnoreFailedSources>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Emoji\emoji-vector-assets.zip" />
  </ItemGroup>
</Project>
